### ISSUE TITLE
Preconfigure OOB application(s) for default EKS cluster

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/terraform-eks#3]
Add preconfigured applications to default EKS cluster.

Good examples:
- [x] Kubernetes Dashboard
~~- [ ] `etcd`~~
~~- [ ] Prometheus (?)~~

**Comment by diemonster** [comment]
After some investigation, it looks like the best path forward is to simply use the `helm` CLI rather than depending on Terraform. The reason being that using Terraform to abstract `helm` accomplishes little more than magic, and in the end, the Terraform helm provider shells out to `helm` anyway.

**Comment by diemonster** [comment]
Moving the bootstrapping of `helm` to the next sprint as it requires a more detailed sense of how we want to address RBAC.
